stenciljs/sass

package.json, src/index.ts
Dart-sass (or just [sass on npm](https://www.npmjs.com/package/sass)) provides a full JavaScript version of sass and will likely be updated sooner than lib-sass if [the documentation](https://sass-lang.com/dart-sass) is correct.  For people that live behind oppressive firewalls that block certain kinds of downloads, this is a lifesaver. 
I have run this version in my local stencil projects without issue, but we also use pretty slim sass functionality (mainly nesting, mixins and variables).
Just offering this as an option should you like to try it over node-sass.
=> refactor: use 'sass' instead of 'node_sass'

src/declarations.ts
Hey,
I've added the node-sass `includePaths` property to the type decorations, in order to fix #14.
There are a lot more props to be added to the decorations: https://www.npmjs.com/package/node-sass
I will be more than happy to add them, just let me know and I will do so.
Best Orlandster
=> Fix - Add node-sass includePaths decoration

src/util.ts
Newer sass compiler versions completely disallow semicolons in .sass files, so the `@import "${injectGlobalPath}";` lines are causing a nonsensical
```
semicolons aren't allowed in the indented syntax.
L1:  \:host
```
error in every component's sass file in the stencil compiler output in the latest version of this package.
This changes it so the `@import` statements generated from injectGlobalPaths use newlines rather than semicolons when the config specifies indentedSyntax.
=> fix(): fix use of injectGlobalPaths in conjunction with indentedSyntax

src/declarations.ts, src/util.ts, test/utils.spec.ts
The injectGlobalPath config will now allow an array of strings, an array of length 2 tuples (arrays), or a combination of both.
The resulting import state will use sass @use syntax instead of the previous @import syntax.
fixes #33
=> @use instead of @import for injectGlobalPath config option

.github/PULL_REQUEST_TEMPLATE.md
this commit adds a pull request template to the repository. it initially
takes the request template from https://github.com/ionic-team/create-stencil/blob/43b4128a91e1870d76bb2768a2ea5266e18dcbdc/.github/PULL_REQUEST_TEMPLATE.md
=> chore(github): add pull request template

.github/PULL_REQUEST_TEMPLATE.md, package.json
this commit updates the `lint.prettier` command to be named `prettier`
to align with the rest of the stencil codebase. similarly, it updates
the 'check' version of running prettier to be 'prettier.dry-run`.
this commit sits atop #76 - I'll wait for the parent to merge before merging this one
=> refactor(format): rename lint.prettier command

package.json
this commit adds volta to the project. it pins node to v16, and npm to
v8. this change only affects the development versions of node/npm, and
does not affect the runtime itself for users of this library
=> chore(infrastructure): add volta to the project

.github/ionic-issue-bot.yml
this commit adds our internal bot 'ionitron' to the stencil-sass
repository. technically, ionitron is already configured for the repo,
but needs a configuration file (this commit) to run.
this commit adapts the ionitron configuration from stencil-store as of
https://github.com/ionic-team/stencil-store/commit/c2a75b2d350fcf2c59458ee777fa0064459c5c3a
=> chore(github): add ionitron bot to the repo

.github/dependabot.yml
Dependabot is (annoyingly) asking us to upgrade to `@types/node@17`
this commit is a follow up to #102, and adds v17 of `@types/node`
to the list of versions that are ignored. this is done as we do not
develop under v17 of node
N/A
=> chore(github): ignore node 17 from type updates

package-lock.json, package.json
this commit increments the minor version of @stencil/core in the peer
dependencies of the package. this change is a result of the stencil team
no longer officially supporting stencil v1.x
BREAKING CHANGE: Drops support for v1.X of Stencil. Stencil projects using
v1.x of `@stencil/core` will need to [migrate to v2.x](https://github.com/ionic-team/stencil/blob/main/BREAKING_CHANGES.md#breaking-changes)
Applications using this library will need to migrate to Stencil v2.  
- Unit tests were run/passed
=> chore(dependencies): increment min stencil version

.github/dependabot.yml
We receive Dependabot updates for packages we don't want to update ATM
this commit updates the dependabot configuration to ignore the following packages:
- `typescript` - ignore versions of typescript the Stencil ecosystem does not support
Taken directly from Stencil core's dependabot config
=> chore(github): ignore unsupported typescript version

.gitignore
See new behavior section
this commit adds the vs code and jetbrains ide settings directories to the project's gitignore file. this is being added as git attempts to surface these as available to check in, which is something we (as the stencil team) do not practice
N/A
=> chore(git): add ide's to gitignore

package-lock.json, package.json
Currently, the package declares a need for Stencil version >=2.0.0. When we install the v3 beta, we get error warnings that we violate this constraint
this commit bumps the values of `package.json#peerDependencies` to accept v3.0.0 of stencil.
This commit was validated in the Ionic Framework with the changes that @alicewriteswrongs made in https://github.com/ionic-team/stencil-ds-output-targets/pull/318. To verify this yourself:
1. Checkout this branch, `npm ci && npm run build && npm pack` <- Also helps validate the changes to the manifest and lockfile are semi-well formed (would show an error message if there was a parse error)
2. Checkout Alice's …
=> chore(deps): support stencil v3

.github/workflows/main.yml
CI only runs on the version of Stencil that is declared in `package-lock.json`
this commit updates our ci workflow to run the build and test steps against multiple versions of stencil. the motivating factors behind this change are as follows:
1. we're preparing to release stencil v3, and would like to catch any regresssions in the library prior to release
2. this library will simultanesouly support stencil v2 and v3 for a period of time, and would like to have ci run on both following the stencil v3.0.0 release
in pursuit of those goals, four versions of stencil are tested:
1. DEFAULT - uses the version of Stencil written in `package-lock.json`, keeping …
=> chore(ci): run multiple versions of stencil

.github/workflows/main.yml
We run CI against more Stencil versions than needed
this commit updates the versions of stencil that ci runs against, following the v3 release of stencil & updating the dev dependency on stencil to v3 in https://github.com/ionic-team/stencil-sass/pull/210
the 'v3-next' version has been removed, as that tag resolves to stencil v3.0.0
the 'latest' verison has been removed, as it now resolves to the same version as 'DEFAULT'
Tailed CI logs
Will need to update the GitHub required checks prior to this landing
=> chore(ci): update stencil versions run post-v3

src/diagnostics.ts, src/index.ts, src/util.ts
This package is largely undocumented
this commit adds jsdoc to the @stencil/sass package to help with transferring knowledge about the package/making it easier to pick up to work on. this is being done prior to the upgrade to sass 1.58.0, which will lead to type changes within the project. this commit is the result of the exercise of the author refamiliarizing themself with the project a bit, rather than a direct dependency of the aforementioned update.
The formatter & type checker should continue to pass (only "functional" changes were explicit types added)
=> chore(jsdoc): document @stencil/sass

.github/dependabot.yml, package-lock.json, package.json
We build/develop the project using Node 16
this commit updates the development dependencies for the project to use node v20. by updating the versions of node/npm that volta uses, the versioning changes are/will be automatically picked up by the ci workflow (as they pull from the volta key in `package.json`)
Unit tests continue to pass
=> chore(node): add node 20 to ci

package-lock.json, package.json
We don't have `engines` specified, which is blocking #324 
this commit adds an engines field to the package to explicitly state what versions of node/npm that are currently supported. the current version of the package supports stencil v2 and up - stencil v2 supported node 12+, which is the justification for such a low version of node/npm in these fields
N/A
=> chore(package): add engines to package.json

package-lock.json, package.json
the motivation for this commit is that renovatebot keeps attempting to update ts to version 5.1.3, despite having a (assumed) valid renovate config. try using a tilde here.
CI only
=> chore(deps): use tilde in typescript dependency

.github/workflows/main.yml, test/utils.spec.ts
If one CI job fails, others may be cancelled without running to completion
this commit prevents the build job from failing fast (i.e. if '2' in the
stencil_version matrix fails, the rest of the jobs will not fail). this
ought to allow us to root our stencil version-based errors more easily
if an error pertains to a single version
https://github.com/ionic-team/stencil-sass/pull/363/commits/ddeeb46836b344c738057403f3d9638d5973d1e3 was temporarily added to this branch to add a little bit of chaos/random error throwing. No jobs were cancelled as a result of errors being thrown
=> chore(ci): don't fail fast for build job 

.gitignore
It's possible to check `tgz` files into the repo
ignore tgz file when testing via `npm pack`
=> chore(repo): ignore .tgz files

src/util.ts, test/utils.spec.ts
While I do not believe this occurs in practice, it is theoretically possible to try to run the plugin if a non-string filename is somehow provided to the plugin's `transform` function
this commit updates the utility method for checking whether the plugin should run on a file, `usePlugin` to return `false` for files that do not end in `.sass`/`.scss`.
Updated unit tests.
The Ionic Framework never actually appears to hit the `return` statement I updated here, and should not be affected by this change
=> fix(utils): only run plugin for sass files

src/index.ts, test/build.spec.ts
Sass compiler dependencies aren't recognised given Windows path.
GitHub Issue Number: https://github.com/ionic-team/stencil/issues/4130
When changing dependent sass files, the compiler now correctly reloads the component with updated styles.
I used a virtual machine and updated the compiled code directly using the reproducible example provided in https://github.com/ionic-team/stencil/issues/4130. Any suggestions how I can provide something better given this bug is related to Windows.
n/a
=> fix(plugin): normalize dependency path

src/util.ts
`@forward` or `@use`-ing 2 files from the same file creates a Type Error.
The file compiles correctly.
=> Handle imports that don’t begin with a “~” correctly

readme.md, src/util.ts, test/utils.spec.ts
GitHub Issue Number: 70
-
-
-
I changed the line in @stencil/sass from `@import` to `@use` with a wildcard in my stencil project and it builds with no errors.
=> fix: change @import to a @use with wildcard
